import Head from "next/head";
import { SetStateAction } from "react";
import CreateCard from "../Components/CreateCard";
import CardsDisplay from "../Components/CardsDisplay";
import type { cardsType } from "./_app";

export default function Home({
  cardsData,
  setCardsData,
}: {
  cardsData: cardsType[];
  setCardsData: React.Dispatch<SetStateAction<cardsType[]>>;
}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col gap-12">
        {cardsData ? (
          <CardsDisplay cardsData={cardsData} />
        ) : (
          <p className="text-center text-3xl">List is empty</p>
        )}
        <CreateCard cardsData={cardsData} setCardsData={setCardsData} />
      </main>
    </>
  );
}
