import Head from "next/head";
import { useState } from "react";
import CreateCard from "../Components/CreateCard";
import CardsDisplay from "../Components/CardsDisplay";

const initialData = [
  {
    id: "id1",
    title: "card1",
    description: "description test 1",
    numberOfQuestions: 20,
    questions: [
      {
        questionId: "Qid1",
        questionBody: "what is question?",
        answer: "this is the answer",
      },
      {
        questionId: "Qid2",
        questionBody: "what is second question?",
        answer: "this is not the answer",
      },
    ],
  },
  {
    id: "id2",
    title: "card2",
    description: "description test 2",
    numberOfQuestions: 30,
    questions: [
      {
        questionId: "Qid1",
        questionBody: "what is question?",
        answer: "this is the answer",
      },
    ],
  },
];

export type cards = {
  id: string;
  title: string;
  description: string;
  numberOfQuestions: number;
  questions: question[];
};

type question = {
  questionId: string;
  questionBody: string;
  answer: string;
};

export default function Home() {
  const [cardsData, setCardsData] = useState<cards[]>(initialData);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col gap-12">
        {cardsData ? (
          <CardsDisplay cardsData={cardsData} />
        ) : (
          <p className="text-center text-3xl">List is empty</p>
        )}
        <CreateCard cardsData={cardsData} setCardsData={setCardsData} />
      </main>
    </>
  );
}
